// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB_6UeR2WV5uYRu8JBP0eSBsDH9DFdbT98',
    appId: '1:1037559408022:web:6e4ffd7cf495c3cfc829b7',
    messagingSenderId: '1037559408022',
    projectId: 'pushnotification-f4402',
    authDomain: 'pushnotification-f4402.firebaseapp.com',
    storageBucket: 'pushnotification-f4402.appspot.com',
    measurementId: 'G-BM093NCY3B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCvFrN6ujv_lCutIXBpNVfZ2DYbK1S4St4',
    appId: '1:1037559408022:android:dba45ccee77bd287c829b7',
    messagingSenderId: '1037559408022',
    projectId: 'pushnotification-f4402',
    storageBucket: 'pushnotification-f4402.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCkuHSVGPUY3N4DvBn88wxPZ7FHNQ10lZk',
    appId: '1:1037559408022:ios:3963420af23f5f50c829b7',
    messagingSenderId: '1037559408022',
    projectId: 'pushnotification-f4402',
    storageBucket: 'pushnotification-f4402.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCkuHSVGPUY3N4DvBn88wxPZ7FHNQ10lZk',
    appId: '1:1037559408022:ios:3963420af23f5f50c829b7',
    messagingSenderId: '1037559408022',
    projectId: 'pushnotification-f4402',
    storageBucket: 'pushnotification-f4402.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB_6UeR2WV5uYRu8JBP0eSBsDH9DFdbT98',
    appId: '1:1037559408022:web:fe5ad6c6c97b548bc829b7',
    messagingSenderId: '1037559408022',
    projectId: 'pushnotification-f4402',
    authDomain: 'pushnotification-f4402.firebaseapp.com',
    storageBucket: 'pushnotification-f4402.appspot.com',
    measurementId: 'G-NJ3T5LSWS1',
  );

}